[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@openzeppelin-up/=lib/openzeppelin-contracts-upgradeable/", "@uniswap-core/=lib/v4-core/src", "@vialabs=lib/npm-contracts/"]
